#!/bin/bash
#
# Decrypt password.
#
# Usage: decrypt_db_password
#
# Options:
#  -e | --envid=..      Specify the environment id. For example: srwd83.
#  -v | --verbose       Print verbose messages.
#
# Examples:
# decrypt_db_password -e srwd83 'fpCkqMNyG/gAhz3x3GDUcWoh/j3BzhexcwP4kYDnnSgjp4YyUMNuS9wKWgQGiRGA90D1mG2361bgGFPuCCb9efmrCo8HUVLjU7COTPCZNYhZ2aqQ9yazVU8VaOiUaxSqVWA5eUJf63qRnN8EVPMNUvcCI7gZqEh6ngLjBNvoq+w\='
#
# Author: minjzhang
#

options=$@

envid=""
verbose=0

#
# Usage
#
function _usage() {
    cat <<EOF
Decrypt password.

Usage: decrypt_db_password

Options:
 -e | --envid=..      Specify the environment id. For example: srwd83.
 -v | --verbose       Print verbose messages.

Examples:
 decrypt_db_password -e srwd83 'fpCkqMNyG/gAhz3x3GDUcWoh/j3BzhexcwP4kYDnnSgjp4YyUMNuS9wKWgQGiRGA90D1mG2361bgGFPuCCb9efmrCo8HUVLjU7COTPCZNYhZ2aqQ9yazVU8VaOiUaxSqVWA5eUJf63qRnN8EVPMNUvcCI7gZqEh6ngLjBNvoq+w\='

EOF
}

#
# Get options
#
OPTS=`getopt -o e:v -l envid:,verbose -- $options`
if [ $? != 0 ]; then
    echo "Error: Unrecognized parameters."
    _usage
    exit 1
fi

eval set -- "$OPTS"

while true ; do
    case "$1" in
        -e | --envid) envid=${2// }; shift 2;;
        -v | --verbose) verbose=1; shift;;
        --) shift; break;;
    esac
done

#
# Print verbose message
#
function _print_verbose_msg {
    verbose_message=$1
    if [[ "$verbose" == 1 ]]; then
        echo $verbose_message
    fi
}

#
# Check if parameters have been set.
#
if [[ "$envid" == "" ]]; then
    echo "Error: Parameter '-e' must be set."
    _usage
    exit 1
fi

export SCRIPTDIR=`dirname $0`
export SCRIPTNAME=`basename $0`

if [[ "${envid}api001.${envid}.com" == `hostname` ]]; then
    export LIB=$SCRIPTDIR/lib/decryptor
    export CLASSPATH="$LIB/log4j-1.2.16.jar:$LIB/commons-codec-1.8.jar:$LIB/commons-io-2.4.jar:$LIB/commons-lang3-3.1.jar:$LIB/com.stubhub.platform.utilities.crypto-lib-1.0.16-SNAPSHOT.jar:$LIB/jcl-over-slf4j-1.6.1.jar:$LIB/slf4j-api-1.6.1.jar:$LIB/slf4j-log4j12-1.6.1.jar"
    export JAVA_HOME="/opt/java"
    $JAVA_HOME/bin/java -classpath $CLASSPATH com.stubhub.platform.crypto.lib.DecryptPassword $@ 2>&1 | grep -v "log4j:WARN"
else
    ssh ${envid}api001.${envid}.com "$SCRIPTDIR/$SCRIPTNAME $options"
fi
