#!/bin/bash

export PATH=/nas/home/minjzhang/bin:$PATH
envid=$1

getroles $envid | grep -v jfw | grep -v lba | grep -v mqs | grep -v sew | grep -v ses | grep -v gns | grep -v scg | while read host
do
if ssh -oPasswordAuthentication=no -ostricthostkeychecking=no -oConnectTimeout=5 $host "sudo /sbin/service kdump status" < /dev/null 2>/dev/null | grep -q "operational"; then
echo "$host - reboot"
ssh -oPasswordAuthentication=no -ostricthostkeychecking=no -oConnectTimeout=5 $host "sudo reboot" < /dev/null 2>/dev/null
else
echo "$host - not ready"
fi
done
