#!/bin/bash
#
# Restart jboss
#
# Usage:
#  restart_jboss ROLE
#
# Author: minjzhang@ebay.com
#

if [[ "$1" == "" ]]; then
    echo "Error: Role not set."
    exit 1
fi

ROLE=$1

if [[ "${ROLE}" == `hostname` ]]; then
    echo "Restarting jboss on ${ROLE}.."
    ps -efl | grep jboss | grep -v grep | grep -v restart_jboss | grep -v tail | awk '{print $4}' | xargs sudo kill -9 &> /dev/null
    sleep 5
    sudo /sbin/service jboss start
    echo "Jboss restarted."
    exit 0
else
    ssh ${ROLE} "/nas/home/minjzhang/bin/restart_jboss ${ROLE}"
fi
