#!/usr/bin/perl
#
# Get a mapping between pool names and pool members
#
# Usage: bigip_get_pools [options]
#
# Options:
#  -e | --env               Specify the environment ID. For example: srwd76.
#  -v | --verbose           Show verbose messages.
#  -h | --help              Show help information.
#
# Examples:
#  bigip_get_pools -e srwd76
#
# Author: minjzhang
#

use strict;
use warnings;

use lib '/nas/reg/lib/perl';
use lib '/nas/home/minjzhang/ops/util/lib';

use Readonly;
use Getopt::Long;
use Data::Dumper;
use BigIP::iControl;
use MIME::Base64;
use Stubhub::BigIP::Pool::Handler qw (
                                        get_env_pool_list
                                    );
use Stubhub::BigIP::System::Util qw (
                                        get_icontrol
                                    );
use Stubhub::Util::Host qw (
                                        get_hostname_by_ip
                                    );

# Get options
my $show_usage = qw{};
my $show_verbose = qw{};
my $envid = qw{};
my $options_okay = GetOptions (
   'e|env=s'     => \$envid,
   'v|verbose'   => \$show_verbose,
   'h|help'      => \$show_usage,
);

#
# Signal Handler
#
$SIG{'INT'} = \&sigIntHandler;

#
# Clean up and exit when catch SIGINT(2)
#
sub sigIntHandler {
    exit;
}

if ( $show_usage ) {
    usage();
    exit 0;
}

#
# Usage
#
sub usage {
   print <<END_OF_HELP
Get a mapping between pool names and pool members

Usage: bigip_get_pools [options]

Options:
 -e | --env               Specify the environment ID. For example: srwd76.
 -v | --verbose           Show verbose messages.
 -h | --help              Show help information.

Examples:
 bigip_get_pools -e srwd76

END_OF_HELP
}

#
# Print pool names and members.
#
sub print_pool_names_members {
    my ( $iControl, $pattern ) = @_;
    my @pool_list = get_env_pool_list( $iControl, $pattern );
    foreach my $pool ( @pool_list ) {
        foreach my $member ($iControl->get_pool_members($pool)) {
            $member =~ s/(.*):.*/$1/;
            print $pool . ":" . get_hostname_by_ip( $member ) . "\n";
        }
    }
}

#
# Parameter validation
#
if ( ! defined $envid) {
    print "Error: The pamameter '-e' must be set.\n";
    usage();
    exit 1;
}

#
# Main
#

my ( $internal_ic, $external_ic ) = get_icontrol( $envid );

print_pool_names_members( $external_ic, $envid );
print_pool_names_members( $internal_ic, $envid );

exit 0;
