#!/bin/bash
#
# Configure block list interactively.
#
# Usage: <script> [options]
# Options:
#  -d | --debug        Print debug messages.
#

options=$@

another_option=0
debug_level=0

#
# Usage
#
function _usage() {
    cat <<EOF

<script> $options

Configure block list interactively.
Usage: <script> [options]
Options:
  -d | --debug        Print debug messages.
EOF
}

#
# Get options
#
OPTS=`getopt -o d -l debug -- $options`
if [ $? != 0 ]; then
    echo "Error: Unrecognized parameters."
    _usage
    exit 1
fi

eval set -- "$OPTS"

while true ; do
    case "$1" in
        -d | --debug) debug_level=1; shift;;
        --) shift; break;;
    esac
done

#
# Print debug message
#
function _print_debug_msg {
    debug_message=$1
    if [[ "$debug_level" == 1 ]]; then
        echo $debug_message
    fi
}

#
# Main
#
HOSTNAME="srwd00lba040.stubcorp.dev"
SCRIPT_PATH="/home/jucao/blacklist"
TMSH_EXEC="tmsh"

if [[ `hostname` != "$HOSTNAME" ]]; then
    echo "Login to $HOSTNAME:"
    echo -n "Username: "
    read username

    ssh $username@$HOSTNAME "$SCRIPT_PATH"
    exit $?
fi

echo "-------------------------------------------------------------------"
echo "| The script helps to configure block/unblock list interactively. |"
echo "-------------------------------------------------------------------"
echo "Enter the list you want to configure:
1. blacklist
2. whitelist
q. quit"
echo -n "> "
read listname
if [[ $listname == "q" ]]; then
    exit 0
fi

if [[ $listname != "1" && $listname != "2" ]]; then
    _usage;
else
    if [[ $listname == "1" ]]; then
        listname="blacklist"
    else
        listname="whitelist"
    fi
fi

echo "Enter the action you want to do to $listname:
1. list
2. add
3. delete
q. quit"
echo -n "> "
read action

if [[ $action == "q" ]]; then
    exit 0
fi

if [[ $action != "1" && $action != "2" && $action != "3" ]]; then
    _usage;
else
    if [[ $action == "1" ]]; then
        action="list"
    elif [[ $action == "2" ]]; then
        action="add"
    else
        action="delete"
    fi
fi

if [[ $action == "list" ]]; then
    `hostname`
    ls $TMSH_EXEC
    $TMSH_EXEC list ltm data-group $listname records | grep '/' | awk '{ print $1 }'
else
    if [[ $action == "add" ]]; then
        echo "Enter the IP address you want to $action to $listname. For example:
1.1.1.0/24
1.1.1.1
1.1.1.1/32"
        echo -n "> "
        read ip_address

        echo "$TMSH_EXEC modify ltm data-group $listname records add {$ip_address}"
        echo -n "Please confirm to execute the command above (y/n): "
        read confirm
        if [[ $confirm == "y" || $confirm == "Y" ]]; then
            $TMSH_EXEC modify ltm data-group $listname records add {$ip_address}
            $TMSH_EXEC save sys config > /dev/null
            echo "Current $listname:"
            $TMSH_EXEC list ltm data-group $listname records | grep "/" | awk '{ print $1 }'
        fi
    elif [[ $action == "delete" ]]; then
        echo "Enter the IP address you want to $action from $listname. For example:
1.1.1.0/24
1.1.1.1
1.1.1.1/32"
        if $TMSH_EXEC list ltm data-group $listname records | grep -q "/"; then
            echo "Current $listname:"
            $TMSH_EXEC list ltm data-group $listname records | grep "/" | awk '{ print $1 }'
        else
            echo "Current $listname is empty."
        fi

        echo -n "> "
        read ip_address

        echo "$TMSH_EXEC modify ltm data-group $listname records delete {$ip_address}"
        echo -n "Please confirm to execute the command above (y/n): "
        read confirm
        if [[ $confirm == "y" || $confirm == "Y" ]]; then
            $TMSH_EXEC modify ltm data-group $listname records delete {$ip_address}
            $TMSH_EXEC save sys config > /dev/null
            if $TMSH_EXEC list ltm data-group $listname records | grep -q "/"; then
                echo "Current $listname:"
                $TMSH_EXEC list ltm data-group $listname records | grep "/" | awk '{ print $1 }'
            else
                echo "Current $listname is empty."
            fi
        fi
    fi
fi

exit 0
