#!/usr/bin/perl
#
# Configure block/unblock list interactively.
#
# Usage: Cloak-Uncloak [options]
#
# Options:
#  -h | --help              Show help information.
#

use strict;
use warnings;

use lib '/nas/reg/lib/perl';
use lib '/nas/home/minjzhang/ops/util/lib';

use Readonly;
use Getopt::Long;
use Net::SSH::Expect;
use Term::ReadKey;

# Get options
my $show_usage = qw{};
my $show_verbose = qw{};
my $options_okay = GetOptions (
   'v|verbose'   => \$show_verbose,
   'h|help'      => \$show_usage,
);

#
# Signal Handler
#
$SIG{'INT'} = \&sigIntHandler;

#
# Clean up and exit when catch SIGINT(2)
#
sub sigIntHandler {
    exit 1;
}

if ( $show_usage ) {
   usage();
   exit 0;
}

#
# Usage
#
sub usage {
   print <<END_OF_HELP

-------------------------------------------------------------------
| Configure block/unblock list interactively.                     |
| Usage: Cloak-Uncloak [options]                                  |
| Options:                                                        |
-------------------------------------------------------------------
END_OF_HELP
}

#
# Login to ssh
#
sub login_ssh {
    my ( $hostname, $username, $password ) = @_;

    my $ssh = Net::SSH::Expect->new(
        host => "$hostname",
        user => "$username",
        password => "$password",
        raw_pty => 1
    );
    my $login_output = $ssh->login();
    if ( $login_output !~ /Last login/ ) {
        die "Login has failed. Login output was $login_output";
    }

    return $ssh;
}

#
# Close ssh connection
#
sub close_ssh {
    my ( $ssh ) = @_;
    $ssh->close();
}

#
# Execute command via ssh mutely
#
sub mute_execute_ssh {
    my ( $ssh, $command ) = @_;
    my $output = $ssh->exec($command);
    my @original_outputs = split(/\n/, $output);
    my @outputs;
    foreach my $line ( @original_outputs ) {
        if ( $line !~ /tmos/ ) {
            chomp $line;
            push(@outputs, $line);
        }
    }
    return @outputs;
}

#
# Execute command via ssh
#
sub execute_ssh {
    my ( $ssh, $command ) = @_;
    my @outputs = mute_execute_ssh( $ssh, $command );
    print join "\n", @outputs;
}

#
# Show current list
#
sub print_list {
    my ( $ssh, $listname ) =@_;
    my @outputs = mute_execute_ssh( $ssh, "list ltm data-group $listname records" );
    my @ip_addresses;
    foreach my $line ( @outputs ) {
        if ( $line =~ /{ }/ ) {
            $line =~ s/^\s*(\S+)\s*{ }\s*$/$1/;
            push( @ip_addresses, $line );
        }
    }
    if ( defined $ip_addresses[0] ) {
        print "\n";
        print "Current $listname:\n";
        print join "\n", @ip_addresses;
        print "\n";
    } else {
        print "$listname is empty.\n";
    }
}

#
# Main
#
Readonly my $HOSTNAME => 'srwd00lba040';
Readonly my $HOSTNAME_CANONICAL => "$HOSTNAME.stubcorp.dev";
Readonly my $TMSH_EXEC => 'tmsh';
Readonly my $LBA_USERNAME => 'root';
Readonly my $LBA_PASSWORD => 'lumnB0tl';

print "-------------------------------------------------------------------
| The script helps to configure block/unblock list interactively. |
-------------------------------------------------------------------
";

print "Username: ";
my $lba_username = <>;
chomp $lba_username;
print "Password: ";
my $lba_password = qw{};
my $key = 0;

# Hide password on the screen
ReadMode(4);
while(ord($key = ReadKey(0)) != 10)
{
    if(ord($key) == 127 || ord($key) == 8) {
        chop($lba_password);
    } elsif(ord($key) < 32) {
    } else {
        $lba_password = $lba_password.$key;
    }
}
chomp $lba_password;
print "\n";
ReadMode(0);

my $ssh = login_ssh($HOSTNAME_CANONICAL, $lba_username, $lba_password);
my $ssh_unlimited = login_ssh($HOSTNAME_CANONICAL, $LBA_USERNAME, $LBA_PASSWORD);

while (1) { # begin of while loop

# Choose list
print "Enter the list you want to configure:
1. blacklist
2. whitelist
q. quit
> ";
my $listname = <>;
chomp $listname;

if ( $listname eq "q" ) {
    close_ssh($ssh);
    close_ssh($ssh_unlimited);
    exit 0;
}
if ( $listname !~ /[12]/ ) {
    usage();
    next;
} else {
    if ( $listname eq "1" ) {
        $listname = "blacklist";
    } else {
        $listname = "whitelist";
    }
}

# Choose action
print "Enter the action you want to do for $listname:
1. list
2. add
3. delete
q. quit
> ";
my $action = <>;
chomp $action;
if ( $action eq "q" ) {
    close_ssh($ssh);
    close_ssh($ssh_unlimited);
    exit 0;
}
if ( $action !~ /[123]/ ) {
    usage();
    next;
} else {
    if ( $action eq "1" ) {
        $action = "list";
    } elsif ( $action eq "2" ) {
        $action = "add";
    } else {
        $action = "delete";
    }
}

# Do action
Readonly my $IP_EXAMPLES =>
"-------------------------------------------------------------------
| 1.1.1.0/24                                                      |
| 1.1.1.1                                                         |
| 1.1.1.1/32                                                      |
| 1.1.1.0/25 1.1.1.0/26                                           |
-------------------------------------------------------------------";

if ( $action eq "list" ) {
    print_list( $ssh, $listname );
} else {
    my $ip_address = qw{};
    my $command = qw{};
    my $confirm = qw{};
    if ( $action eq "add" ) {
        print "Enter the IP address you want to $action to $listname. For example:\n";
        print "$IP_EXAMPLES\n";
        print "> ";
        $ip_address = <>;
        chomp $ip_address;
        $command = "modify ltm data-group $listname records add {$ip_address}";
        print "$command\n";
        print "Please confirm to execute the command above (y/n): ";
        $confirm = <>;
        if ( $confirm =~ /y/i ) {
            execute_ssh($ssh, $command);
            mute_execute_ssh($ssh_unlimited, "$TMSH_EXEC save sys config");
            print_list( $ssh, $listname );
        }
    } elsif ( $action eq "delete" ) {
        print "Enter the IP address you want to $action from $listname. For example:\n";
        print "$IP_EXAMPLES\n";
        print_list( $ssh, $listname );
        print "> ";
        $ip_address = <>;
        chomp $ip_address;
        $command = "modify ltm data-group $listname records delete {$ip_address}";
        print "$command\n";
        print "Please confirm to execute the command above (y/n): ";
        $confirm = <>;
        if ( $confirm =~ /y/i ) {
            execute_ssh($ssh, $command);
            mute_execute_ssh($ssh_unlimited, "$TMSH_EXEC save sys config");
            print_list( $ssh, $listname );
        }
    }
}

} # end of while loop

close_ssh($ssh);
close_ssh($ssh_unlimited);
exit 0;
