#!/bin/sh

dry_run=0

if [[ "$1" == "-d" ]]; then
    dry_run=1
fi

umount_cmd='umount -l /nas/reg/lib/perltest'
mount_cmd='mount -o rw,nosuid,nodev,_netdev,rsize=32768,wsize=32768,timeo=35,retrans=5,soft,tcp napMGT.stubcorp.dev:/REG/lib/perl5.8 /nas/reg/lib/perltest'
host=`hostname`

if [[ "$dry_run" == "1" ]]; then
    echo "Host: $host"
    echo "Command: $umount_cmd"
    echo "Command: $mount_cmd"
else
    $umount_cmd 2&> /dev/null
    $mount_cmd
    if df /nas/reg/lib/perltest | grep -q perl5.8; then
        echo "$host: success"
    else
        echo "$host: failure"
    fi
fi


