#!/bin/bash
#
# To validate if email can be sent via strongmail server.
#
# Usage: email_validate [options]
#
# Options:
#  -m | --email=..     Specify the email address to check.
#  -e | --env=..       Specify the environment to check.
#  -d | --debug        Print debug messages.
#
# Author: minjzhang@ebay.com
#

options=$@

email_address=""
envid=""
debug_level=0

#
# Usage
#
function _usage() {
    cat <<EOF
email_validate $options

$*
Usage: email_validate [options]

Options:
  -m | --email=..     Specify the email address to check.
  -e | --env=..       Specify the environment to check.
  -d | --debug        Print debug messages.
EOF
}

#
# Get options
#
OPTS=`getopt -o m:e:d -l email:,env:,debug -- $options`
if [ $? != 0 ]; then
    echo "Error: Unrecognized parameters."
    _usage
    exit 1
fi

eval set -- "$OPTS"

while true ; do
    case "$1" in
        -m | --email) email_address=${2// }; shift 2;;
        -e | --env) envid=${2// }; shift 2;;
        -d | --debug) debug_level=1; shift;;
        --) shift; break;;
    esac
done

#
# Print debug message
#
function _print_debug_msg {
    debug_message=$1
    if [[ "$debug_level" == 1 ]]; then
        echo $debug_message
    fi
}

#
# Query email logs in database
#
function query_email_logs_in_db {
    . /nas/home/minjzhang/bin/base

    $BIN/query_email_logs -m $email_address > /dev/null
    rc=$?

    if [[ "$rc" == 0 ]]; then
        echo "Find email logs in database:                              PASS"
    else
        echo "Find email logs in database:                              FAIL"
    fi
}

#
# Check the logs in JBoss log on JOB
#
function query_email_logs_in_job_jboss {
    JOB_HOST=${envid}job001.${envid}.com
    email_jboss_log=`ssh $JOB_HOST "grep $email_address /opt/jboss/server/default/log/jboss.*" < /dev/null`
    if [[ $email_jboss_log == "" ]]; then
        echo "Find logs related to email address in JOB jboss log:      FAIL"
        return 1
    else
        echo "Find logs related to email address in JOB jboss log:      PASS"
    fi

    if echo $email_jboss_log | grep -q "priority=ERROR"; then
        echo "No errors in related to email address in JOB jboss log:   FAIL"
        _print_debug_msg "[debug] echo $email_jboss_log"
    else
        echo "No errors in related to email address in JOB jboss log:   PASS"
    fi
}

function check_mqm_queue {
    . /nas/home/minjzhang/bin/base

    $BIN/purge_mqm -e $envid -l > /dev/null
    rc=$?

    if [[ "$rc" == 0 ]]; then
        echo "Check no MQM pending messages:                            PASS"
    else
        echo "Check no MQM pending messages:                            FAIL"
    fi
}

#
# Check network settings for mqm/mqs, including subnet mask
#
function check_mqm_ifconfig {
    . /nas/home/minjzhang/bin/base

    $BIN/check_mqm_ifconfig -e $envid > /dev/null
    rc=$?

    if [[ "$rc" == 0 ]]; then
        echo "Check subnet mask for MQM/MQS:                            PASS"
    else
        echo "Check subnet mask for MQM/MQS:                            FAIL"
    fi
}

#
# Check /etc/passwd file on srwd00mri001 to ensure enough permission
#
function check_mri_passwd {
    MRI_HOST=srwd00mri001.stubcorp.dev

    passwd_line=`ssh $MRI_HOST "grep $envid /etc/passwd" < /dev/null`
    user=`echo $passwd_line | awk -F: '{ print $1}'`
    auth1=`echo $passwd_line | awk -F: '{ print $3}'`
    auth2=`echo $passwd_line | awk -F: '{ print $4}'`
    home_dir=`echo $passwd_line | awk -F: '{ print $6}'`

    if [[ "$user" == "strongmailbcc_${envid}" && "$auth1" == "20128" \
            && "$auth2" == "20128" && "$home_dir" == \
            "/nas/strongmail/Maildir_${envid}" ]]; then
        echo "Check MRI /etc/passwd:                                    PASS"
    else
        echo "Check MRI /etc/passwd:                                    FAIL"
        _print_debug_msg "[debug] $passwd_line"
    fi
}

#
# Check new mail directory on JOB
#
function check_mail_dir_new {
    JOB_HOST=${envid}job001.${envid}.com

    file_count=`ssh $JOB_HOST "sudo ls /nas/strongmail/Maildir_srwd63/Maildir/new | wc -l"`
    if [[ "$file_count" == 0 ]]; then
        echo "Check new mail directory is empty:                        PASS"
    else
        echo "Check new mail directory is empty:                        FAIL"
        _print_debug_msg "[debug] File count: $file_count"
    fi
}

#
# Main
#

check_mqm_ifconfig
check_mqm_queue
check_mri_passwd
check_mail_dir_new
if [[ "$email_address" != "" ]]; then
    query_email_logs_in_db
    query_email_logs_in_job_jboss
fi
print "Check DB partition.\n";

exit 0
