#!/bin/bash
#
# Get the database connections for the environments.
# Please run 'go' script at first.
#
# Usage:
#  getdb
#
# Author: minjzhang@ebay.com
#

DB_CONNECTION=`ssh $act "cat $ENVPP" | grep "SERVICE_NAME = D" | head -n 1`
echo $DB_CONNECTION | sed "s/.*(SERVICE_NAME = \([^)]*\)).*/\1/"
echo $DB_CONNECTION | sed "s/.*(HOST=\([^)]*\)).*/\1/"
echo $DB_CONNECTION | sed "s/.*(PORT=\([^)]*\)).*/\1/"
echo $DB_CONNECTION | sed "s/.*(PROTOCOL=\([^)]*\)).*/\1/"
