#!/bin/bash
#
# Set all the variables related to the specified environment
#
# Usage:
#  setenv ENVID
#
# Options:
#  NA
#
# Example:
#  setenv 59
#
# Author: minjzhang@ebay.com
#

. /nas/home/minjzhang/bin/base

if [ "$1" == "" ]; then
    echo "Error: Lack of variables. Please check the usage."
    exit 1
fi

export ENVID=$1
ENVPREFIX=srwd

#
# Set roles
#
roles=`$BIN/getroles`
for ROLE in $roles
do
    export $ROLE=${ENVPREFIX}${ENVID}${ROLE}001.${ENVPREFIX}${ENVID}.com
    export ${ROLE}jmx=http://${ENVPREFIX}${ENVID}${ROLE}001.${ENVPREFIX}${ENVID}.com/jmx-console
done

#
# Set sanity check
#
export PS1="[\u:${ENVPREFIX}${ENVID}@\h \W]\$ "

#
# Set JBoss variables
#
export JBDF="/opt/jboss/server/default"
export JBDP="${JBDF}/deploy"
export JBLG="${JBDF}/log/jboss.log"

#
# Set Apache variables
#
export APLG="/var/log/httpd"

#
# Set Stubhub properties
#
export ENVPP="/etc/stubhub/properties/ENV.stubhub.properties"
export STCK="http://${ENVPREFIX}${ENVID}hub001.${ENVPREFIX}${ENVID}.com:8080/jmxsitemgr/dashboard.jsp"

#
# Useful URL
#
export SOLR="http://${ENVPREFIX}${ENVID}mci001.${ENVPREFIX}${ENVID}.com/solr"
export MQ="http://${ENVPREFIX}${ENVID}mqm001.${ENVPREFIX}${ENVID}.com:8161/admin/queues.jsp"
export STBTX="https://stubtex.${ENVPREFIX}${ENVID}.com/cstool"
