#!/bin/bash
#
# Set all the variables related to the specified environment
#
# Usage: setenv [options] ENVID
# Options:
#  -t  --type=..    The type of the environment. Values can be srwd and srwe. Default value is srwd.
#  -d  --debug      Print debug messages
#
# Example:
#  setenv 59
#
# Author: minjzhang@ebay.com
#

. /nas/home/minjzhang/bin/base

options=$@

debug_level=0
ENVPREFIX=srwd

#
# Usage
#
function _usage() {
    cat <<EOF
setenv $options
$*
 Usage: setenv [options] ENVID
 Options:
  -t  --type=..    The type of the environment. Values can be srwd and srwe. Default value is srwd.
  -d  --debug      Print debug messages
EOF
}

#
# Get options
#
OPTS=`getopt -o t:d -l type:,debug -- $options`
if [ $? != 0 ]
then
    echo "Error: Unrecognized parameters."
    _usage
    return 1
fi

eval set -- "$OPTS"

while true ; do
    case "$1" in
        -t | --type) ENVPREFIX=`echo $2 | awk '{print $1}'`; ENVID=`echo $2 | awk '{print $2}'`; shift 2;;
        -d | --debug) debug_level=1; shift;;
        --) shift; break;;
    esac
done

#
# Print debug message
#
function _print_debug_msg {
    debug_message=$1
    if [[ "$debug_level" == 1 ]]; then
        echo $debug_message
    fi
}

#
# Main
#
if [[ "$1" == "" && "$ENVID" == "" ]]; then
    echo "Error: Lack of ENVID."
    _usage
    return 1
fi

if [[ "$1" != "" ]]; then
    export ENVID=$1
fi

#
# Set roles
#
DEV_HOSTS=/nas/reg/etc/dev-qa-hosts
roles=`grep ${ENVPREFIX}${ENVID} ${DEV_HOSTS} | sort | uniq`
for ROLE in $roles
do
    shortcut=`echo $ROLE | sed "s/${ENVPREFIX}${ENVID}\([a-z]*\)[0-9]\{3\}.*/\1/"`
    shortcut_long=`echo $ROLE | sed "s/${ENVPREFIX}${ENVID}\([a-z]*[0-9]\{3\}\).*/\1/"`
    if echo $shortcut | grep -q "^[a-z]\+$"; then
        export $shortcut=$ROLE
        export ${shortcut}jmx="http://${ROLE}/jmx-console/"
        export ${shortcut}chk="http://${ROLE}/jmx-console/HtmlAdaptor?action=invokeOpByName&name=jboss.system%3Aservice%3DMainDeployer&methodName=checkIncompleteDeployments"
    fi
    export $shortcut_long=$ROLE
    export ${shortcut_long}jmx="http://${ROLE}/jmx-console/"
    export ${shortcut_long}chk="http://${ROLE}/jmx-console/HtmlAdaptor?action=invokeOpByName&name=jboss.system%3Aservice%3DMainDeployer&methodName=checkIncompleteDeployments"
done

#
# Set sanity check
#
export PS1="[\u:${ENVPREFIX}${ENVID}@\h \W]\$ "

#
# Set JBoss variables
#
export JBDF="/opt/jboss/server/default"
export JBDP="${JBDF}/deploy"
export JBLG="${JBDF}/log/jboss.log"
export JBLGDIR="${JBDF}/log"

#
# Set Apache variables
#
export APLG="/var/log/httpd"

#
# Set Stubhub properties
#
export ENVPP="/etc/stubhub/properties/ENV.stubhub.properties"
export STCK="http://${ENVPREFIX}${ENVID}hub001.${ENVPREFIX}${ENVID}.com:8080/jmxsitemgr/dashboard.jsp"

#
# Useful URL
#
export SOLR="http://${ENVPREFIX}${ENVID}mci001.${ENVPREFIX}${ENVID}.com/solr"
export SLR="http://${ENVPREFIX}${ENVID}mci001.${ENVPREFIX}${ENVID}.com/solr"
export MCISLR="http://${ENVPREFIX}${ENVID}mci001.${ENVPREFIX}${ENVID}.com/solr"
export LCXSLR="http://${ENVPREFIX}${ENVID}lcx001.${ENVPREFIX}${ENVID}.com/solr"
export MQ="http://${ENVPREFIX}${ENVID}mqm001.${ENVPREFIX}${ENVID}.com:8161/admin/queues.jsp"
export MQMMQ="http://${ENVPREFIX}${ENVID}mqm001.${ENVPREFIX}${ENVID}.com:8161/admin/queues.jsp"
export LCMMQ="http://${ENVPREFIX}${ENVID}lcm001.${ENVPREFIX}${ENVID}.com:8161/admin/queues.jsp"
export STBTX="https://stubtex.${ENVPREFIX}${ENVID}.com/cstool"
export REIDX="http://${ENVPREFIX}${ENVID}lcm001.${ENVPREFIX}${ENVID}.com/jmx-console/HtmlAdaptor?action=inspectMBean&name=com.stubhub.framework.lcsmaster%3Aservice%3DrequestChainServletMonitor"
export MYXRT="http://${ENVPREFIX}${ENVID}myx001.${ENVPREFIX}${ENVID}.com/jmx-console/HtmlAdaptor?action=inspectMBean&name=Stubhub-Properties-StubhubMYXRole%3Aname%3DStubHub+Properties"
