#!/bin/bash
#
# Executes command with a timeout
#
# Usage: timeout [seconds] [command]
#
# Author: minjzhang
#

#
# Usage
#
function _usage() {
    cat <<EOF

timeout $options
$*
Executes command with a timeout

Usage: timeout [seconds] [command]

EOF
}

#
# Main
#

time=$1
shift;

# start the command in a subshell to avoid problem with pipes
# (spawn accepts one command)
command="/bin/sh -c \"$@\""

expect -c "set echo \"-noecho\"; set timeout $time; spawn -noecho $command; expect timeout { exit 1} eof { exit 0}"

if [ $? = 1 ]; then
    echo "Timeout after ${time} seconds"
fi

exit 0
