#!/usr/bin/perl -w
#
# Diff between token table properties.
#
# Usage: token-table-diff [options]
#
# Options:
#  -s | --source            The source environment id to diff. For example: srwd30.
#  -t | --target            The target environment id to diff. For example: srwd40.
#  -v | --verbose           Show verbose messages.
#  -h | --help              Show help information.
#
# Examples:
#  token-table-diff -s srwd30 -t srwd40
#
# Author: minjzhang
#

use strict;

use lib '/nas/reg/lib/perl';

use Getopt::Long;
use File::Temp qw( tempfile );
use REG::P4::Util qw(
                    $P4OPTS
                    branch_path
                    delete_dynamic_client
                    dynamic_client
                    is_valid_branch
                    logged_in
                    p4cmd
                    );
use REG::Util qw( mktmpdir rm_rf );

sub clean_die ( @ ) ;

# Get options
my $show_usage = qw{};
my $show_verbose = qw{};
my $source_envid = qw{};
my $target_envid = qw{};

my $options_okay = GetOptions (
   's|source=s'  => \$source_envid,
   't|target=s'  => \$target_envid,
   'v|verbose'   => \$show_verbose,
   'h|help'      => \$show_usage,
);

if ( $show_usage ) {
   usage();
}

#
# Usage
#
sub usage {
   print <<END_OF_HELP
Diff between token table properties.

Usage: token-table-diff [options]

Options:
 -s | --source            The source environment id to diff. For example: srwd30.
 -t | --target            The target environment id to diff. For example: srwd40.
 -v | --verbose           Show verbose messages.
 -h | --help              Show help information.

Examples:
 token-table-diff -s srwd30 -t srwd40

Author: minjzhang

END_OF_HELP
}

#
# Parameter validation
#
if ( ! defined $source_envid || ! defined $target_envid ) {
    print "Error: Pamater '-s' and '-t' must be set.\n";
    usage();
    exit 1;
}

#
# Filter variables related to environment
#
sub filter_variables {
    my ( $line, $envid, $db_host_id ) = @_;
    $line =~ s/\s*//g;
    $line =~ s/$envid/<ENVID>/g;
    if ( $db_host_id == "08" ) {
        $line =~ s/\$<delphix_host01>/<DELPHIX_HOST>/;
        $envid =~ s/srw[de]([0-9]+)/$1/;
        $line =~ s/\$<delphix_db_prefix>$envid/<DELPHIX_SID>/;
    }
    if ( $db_host_id == "16" ) {
        $line =~ s/\$<delphix_host02>/<DELPHIX_HOST>/;
        $envid =~ s/srw[de]([0-9]+)/$1/;
        $line =~ s/\$<delphix_db_prefix_16>$envid/<DELPHIX_SID>/;
    }
    if ( $db_host_id == "19" ) {
        $line =~ s/\$<delphix_host03>/<DELPHIX_HOST>/;
        $envid =~ s/srw[de]([0-9]+)/$1/;
        $line =~ s/\$<delphix_db_prefix_19>$envid/<DELPHIX_SID>/;
    }

    return $line;
}

#
# Get database connection information
# TODO how to get PE environment db connection
#
sub get_db_connection {
    my ( $envid ) = @_;
    if ( $envid !~ m/srwd.*/ ) {
        return;
    }
    $envid =~ s/srwd([0-9]+)/$1/;
    my $db_instance = "DE$envid";

    my $tnsnames="/nas/home/oracle/OraHome/network/admin/tnsnames.ora";
    open TNSNAMES_FH, "<$tnsnames" or die $!;

    while ( my $line = <TNSNAMES_FH> ) {
        if ( $line =~ m/D[0-9]{2}$db_instance/ ) {
            $line =~ s/D([0-9]{2})$db_instance.*/$1/;
            close TNSNAMES_FH;
            return $line;
        }
    }

    close TNSNAMES_FH;
    return;
}

#
# Check out token-table from perforce depot
#
sub check_out_token_table {
    $ENV{ PATH } = ':/usr/local/bin'
        . ':/opt/java/bin'
        . ':/opt/ant/bin';

    my $dynamic_perforce_client;
    my $PERFORCE_DEFAULT_SERVER_SRW = "perforce.stubcorp.dev";
    my $PERFORCE_DEFAULT_PORT_NUMBER = "1666";
    defined $ENV{ P4CONFIG } and $ENV{ P4CONFIG } = "";

    my $PERFORCE_CLIENTS_DIRECTORY = "/tmp";
    my $dynamic_client_try = "$PERFORCE_CLIENTS_DIRECTORY/p4-dynamic-wc-". '${timestamp}';
    my $DYNAMIC_PERFORCE_CLIENT_ROOT_DIRECTORY = mktmpdir ({
            try => $dynamic_client_try,
            perms => 0750,
        });
    not defined $DYNAMIC_PERFORCE_CLIENT_ROOT_DIRECTORY and clean_die "could not create root directory of dynamic perforce client;"
        , " first attempt tried to create '$dynamic_client_try'";

    $P4OPTS = "-u build -p $PERFORCE_DEFAULT_SERVER_SRW:$PERFORCE_DEFAULT_PORT_NUMBER";

    $dynamic_perforce_client = dynamic_client({
            depot   => 'depot',
            root    => $DYNAMIC_PERFORCE_CLIENT_ROOT_DIRECTORY,
        });

    $P4OPTS = "$P4OPTS -c $dynamic_perforce_client->{ Client }";

    maybe_log_into_perforce();

    sync_files();


    clean_perforce_client( $dynamic_perforce_client );

    return "$DYNAMIC_PERFORCE_CLIENT_ROOT_DIRECTORY/internal/dev/properties/tokenization/token-table-env-stubhub-properties";
}

sub clean_up {
    my ( $temp_dir ) = @_;
    `/bin/rm -rf $temp_dir`;
    #rm_rf( $dynamic_client_try );
}

sub clean_perforce_client {
    my ( $dynamic_perforce_client, ) = @_;
    if ( defined $dynamic_perforce_client ) {
        delete_dynamic_client({
            client => $dynamic_perforce_client,
            p4opts => $P4OPTS,
        });
    }
}

sub sync_files {
    my $func = ( caller 0 )[ 3 ];
    my $ESP_TOKEN_TABLE_DEPOT_PATH="//internal/dev/properties/tokenization/token-table-env-stubhub-properties";

    my $cmd = p4cmd( "sync $ESP_TOKEN_TABLE_DEPOT_PATH" );

    my @results = qx{ $cmd 2>&1 };
    my $status = $? >> 8;

    my $results = join( "", @results );

    $status != 0 and clean_die "cmd returned non-zero status; cmd => '$cmd';",
        " status => $status; output => '$results'";

    return;
}

sub maybe_log_into_perforce {

    my $BATCHMODE = ( not -t );

    # log into perforce if not already logged in
    if ( not logged_in() ) {
        if ( $BATCHMODE ) {
            clean_die "not logged into perforce; using => $P4OPTS";
        } else {
            system p4cmd( 'login' );
        }
    }

    my $status = $? >> 8;
    $status != 0 and clean_die "could not log into perforce using => $P4OPTS";

    return;
}

#
# Main
#

my $token_table_stubhub = check_out_token_table();

open TOKEN_TABLE_STUBHUB, "<$token_table_stubhub" or die $!;

my $source_fh = new File::Temp( UNLINK => 1 );
my $target_fh = new File::Temp( UNLINK => 1 );

open $source_fh, ">$source_fh" or die $!;
open $target_fh, ">$target_fh" or die $!;

my $in_source_node = 0;
my $in_target_node = 0;

my @source_properties = ();
my @target_properties = ();

while ( my $line = <TOKEN_TABLE_STUBHUB> ) {
    # If matching the begining of source environment node
    if ( $line =~ m/^\s*<$source_envid>\s*$/ ) {
        $in_source_node = 1;
        next;
    }
    # If matching the end of source environment node
    if ( $line =~ m/^\s*<\/$source_envid>\s*$/ ) {
        $in_source_node = 0;
        next;
    }
    # If matching the begining of target environment node
    if ( $line =~ m/^\s*<$target_envid>\s*$/ ) {
        $in_target_node = 1;
        next;
    }
    # If matching the end of source environment node
    if ( $line =~ m/^\s*<\/$target_envid>\s*$/ ) {
        $in_target_node = 0;
        next;
    }

    # Not print empty line and comment line
    if ( $line !~ m/^\s*$/ && $line !~ m/^\s*#/ ) {
        if ( $in_source_node == 1 ) {
            my $db_host_id = get_db_connection($source_envid);
            $line = filter_variables($line, $source_envid, $db_host_id);
            push(@source_properties, $line);
        }
        if ( $in_target_node == 1 ) {
            my $db_host_id = get_db_connection($target_envid);
            $line = filter_variables($line, $target_envid, $db_host_id);
            push(@target_properties, $line);
        }
    }
}

print $source_fh join("\n", sort( @source_properties ) );
print $target_fh join("\n", sort( @target_properties ) );
$source_fh->flush();
$target_fh->flush();

print "$source_envid <==> $target_envid:\n";
print "-----------------------------------\n";
my $result=`/usr/bin/diff -y --suppress-common-lines $source_fh $target_fh`;
print $result;

close TOKEN_TABLE_STUBHUB;
close $source_fh;
close $target_fh;

clean_up( $token_table_stubhub );

exit 0;
