#!/bin/bash

#
# Usage
#
function _usage() {
    cat <<EOF

Usage:
 getsnapshot [snapshot_name]

Example
 getsnapshot orig

EOF
}

snapshot_name=$1
script_dir=`dirname $0`
snapshot_prefix='sysctl.conf.'

if [[ "$snapshot_name" == "" ]]; then
    echo "Error: please specify the snapshot name."
    _usage
    exit 1
fi

if [ ! -e ${snapshot_prefix}${snapshot_name} ]; then
    echo "Error: the snapshot [${snapshot_name}] not exist."
    _usage
    exit 1
fi

/usr/bin/sudo /sbin/sysctl -e -p ${snapshot_prefix}${snapshot_name} >& /dev/null
